version: '3.7'

services:
  db:
    image: mysql:8.0.26
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz@WSX
      MYSQL_USER: glen
      MYSQL_PASSWORD: 1qaz@WSX
      MYSQL_DATABASE: jiyoung_shopee
    volumes:
      - ./db_dump:/var/lib/mysql
      - ./mysql_conf:/etc/mysql/conf.d
      - ./config/mysql_init:/docker-entrypoint-initdb.d
    networks:
      shopee-network:
        ipv4_address: 172.21.0.2

  redis:
    image: redis:6.2.5
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./config/redis:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      shopee-network:
        ipv4_address: 172.21.0.3

networks:
  shopee-network:
    name: shopee-network
    driver: bridge
    ipam:
        driver: default
        config:
            - subnet: 172.21.0.0/16
              gateway: 172.21.0.1
