definitions:
  backstagedto.JwtInfoDTO:
    properties:
      id:
        minimum: 6
        type: integer
      name:
        minLength: 4
        type: string
    type: object
  backstagedto.JwtTokenDTO:
    properties:
      refreshToken:
        type: string
      token:
        type: string
    type: object
  backstagedto.LoginDTO:
    properties:
      loginName:
        minLength: 4
        type: string
      password:
        minLength: 6
        type: string
    type: object
  backstagedto.LoginResponseDTO:
    properties:
      authorityJwt:
        $ref: '#/definitions/backstagedto.JwtTokenDTO'
      userInfo:
        $ref: '#/definitions/backstagedto.JwtInfoDTO'
    type: object
  backstagedto.UserDTO:
    properties:
      UserType:
        description: 是否為系統用戶
        type: boolean
      email:
        description: Email
        type: string
      loginName:
        description: 登入帳號
        minLength: 4
        type: string
      name:
        description: 使用者名稱
        minLength: 4
        type: string
      password:
        description: 密碼
        minLength: 6
        type: string
      remark:
        description: 備註
        type: string
      status:
        description: 帳號狀態(false停用 true正常)
        type: boolean
    type: object
  dto.BaseResponseDTO:
    properties:
      data: {}
      msg:
        type: string
    type: object
  dto.PageDTO:
    properties:
      count:
        type: integer
      page:
        type: integer
      pageLimit:
        type: integer
      search:
        type: string
      searchCategory:
        type: string
      sort:
        type: string
      sortColumn:
        type: string
    type: object
  forestagedto.BaseConfigDTO:
    properties:
      imgUrl:
        type: string
    type: object
  forestagedto.BaseForestageConfigDTO:
    properties:
      baseConfig:
        $ref: '#/definitions/forestagedto.BaseConfigDTO'
    type: object
  forestagedto.CarouselDTO:
    properties:
      carousels:
        items:
          $ref: '#/definitions/forestagedto.CarouselData'
        type: array
    type: object
  forestagedto.CarouselData:
    properties:
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      url:
        type: string
      weight:
        type: integer
    type: object
  forestagedto.CategoryDTO:
    properties:
      category:
        items:
          type: string
        type: array
    type: object
  forestagedto.ProductionDTO:
    properties:
      pageData:
        $ref: '#/definitions/dto.PageDTO'
      productionList:
        items:
          $ref: '#/definitions/forestagedto.ProductionData'
        type: array
    type: object
  forestagedto.ProductionData:
    properties:
      categories:
        type: string
      createTime:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      images:
        type: string
      name:
        type: string
      options:
        type: string
      price:
        type: integer
      priceMin:
        type: integer
      productId:
        type: integer
      url:
        type: string
    type: object
  forestagedto.ProductionDetailDTO:
    properties:
      production:
        $ref: '#/definitions/forestagedto.ProductionDetailData'
    type: object
  forestagedto.ProductionDetailData:
    properties:
      attribute:
        type: string
      categories:
        type: string
      createTime:
        type: string
      description:
        type: string
      historicalSold:
        type: integer
      id:
        type: integer
      image:
        type: string
      images:
        type: string
      likedCount:
        type: integer
      name:
        type: string
      options:
        type: string
      price:
        type: integer
      priceMin:
        type: integer
      productId:
        type: integer
      stock:
        type: integer
      url:
        type: string
    type: object
  forestagedto.ProductionRankDTO:
    properties:
      productionList:
        items:
          $ref: '#/definitions/forestagedto.ProductionRankData'
        type: array
    type: object
  forestagedto.ProductionRankData:
    properties:
      amount:
        type: integer
      categories:
        type: string
      createTime:
        type: string
      description:
        type: string
      historicalSold:
        type: integer
      id:
        type: integer
      image:
        type: string
      images:
        type: string
      likedCount:
        type: integer
      name:
        type: string
      options:
        type: string
      price:
        type: integer
      priceMin:
        type: integer
      productId:
        type: integer
      stock:
        type: integer
      url:
        type: string
      weight:
        type: integer
    type: object
info:
  contact: {}
paths:
  /admin/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/backstagedto.LoginDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backstagedto.LoginResponseDTO'
      summary: Backstage login
      tags:
      - Backstage
  /backstage/user/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/backstagedto.UserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.BaseResponseDTO'
      summary: Backstage UserLogin
      tags:
      - Backstage
  /carousel/list:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/forestagedto.CarouselDTO'
      summary: Carousel
      tags:
      - Forestage
  /category/list:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/forestagedto.CategoryDTO'
      summary: Category
      tags:
      - Forestage
  /forestage/config:
    get:
      consumes:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/forestagedto.BaseForestageConfigDTO'
      summary: Forestage config
      tags:
      - Forestage
  /production/{id}:
    get:
      consumes:
      - application/json
      operationId: "1"
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/forestagedto.ProductionDetailDTO'
      summary: Production detail
      tags:
      - Forestage
  /production/list:
    get:
      consumes:
      - application/json
      parameters:
      - default: 1
        description: int default
        in: query
        name: page
        required: true
        type: integer
      - description: int enums
        enum:
        - 15
        - 20
        - 30
        - 40
        - 50
        in: query
        name: pageLimit
        required: true
        type: integer
      - description: string enums
        enum:
        - asc
        - desc
        in: query
        name: sort
        required: true
        type: string
      - description: string enums
        enum:
        - PName
        - PId
        - PCategory
        - PCreTime
        in: query
        name: sortColumn
        required: true
        type: string
      - default: ""
        description: string default
        in: query
        name: search
        type: string
      - default: ""
        description: string default
        in: query
        name: searchCategory
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/forestagedto.ProductionDTO'
      summary: Production list
      tags:
      - Forestage
  /production/rank/{count}:
    get:
      consumes:
      - application/json
      operationId: "10"
      parameters:
      - description: count
        in: path
        name: count
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/forestagedto.ProductionRankDTO'
      summary: Production rank
      tags:
      - Forestage
swagger: "2.0"
